const char* awp[] = { "none",
"Asiimov",
"Dragon Lore",
"Fever Dream",
"Medusa",
"HyperBeast",
"Boom",
"Lightning Strike",
"Pink DDpat",
"Corticera",
"Redline",
"Manowar",
"Graphite",
"Electric Hive",
"Sun in Leo",
"Hyper Beast",
"Pit viper",
"Phobos",
"Elite Build",
"Worm God",
"Oni Taiji",
"Fever Dream" };
const char* scout[] = { "none",
"Lichen Dashed",
"Dark Water",
"Blue Spruce",
"Sand Dune",
"Palm",
"Mayan Dreams",
"Blood in the Water",
"Tropical Storm",
"Acid Fade",
"Slashed",
"Detour",
"Abyss",
"Big Iron",
"Necropos",
"Ghost Crusader",
"Dragonfire" };
const char* scars[] = { "none",
"Splash Jam",
"Storm",
"Contractor",
"Carbon Fiber",
"Sand Mesh",
"Palm",
"Crimson Web",
"Cardiac",
"Army Sheen",
"Cyrex",
"Grotto",
"Bloodsport" };
const char* glock[] = { "none",
"Fade",
"Dragon Tattoo",
"Twilight Galaxy",
"Wasteland Rebel",
"Water Elemental",
"Off World",
"Weasel",
"Royal Legion",
"Grinder",
"Steel Disruption",
"Brass",
"Ironwork",
"Bunsen Burner",
"Reactor" };
const char* g3sg1[] = { "none",
"Hunter",
"The Executioner",
"Terrace",
"Neon Kimono",
"Orange Kimono",
"Predator",
"Chronos"
};
const char* duals[] = { "none",
"Panther",
"Dualing Dragons",
"Cobra Strike",
"Royal Consorts",
"Duelist" };
const char* deagle[] = { "none",
"Blaze",
"Kumicho Dragon",
"Oxide Blaze",
"Golden Koi",
"Cobalt Disruption",
"Directive" };
const char* usp[] = { "none",
"Neo-Noir",
"Cyrex",
"Orion",
"Kill Confirmed",
"Overgrowth",
"Caiman",
"Serum",
"Guardian",
"Road Rash" };
const char* ak[] = { "none",
"Fire serpent",
"Fuel Injector",
"Bloodsport",
"Vulcan",
"Case hardened",
"Hydroponic",
"Aquamarine Revenge",
"Frontside Misty",
"Point Disarray",
"Neon Revolution",
"Red laminate",
"Redline",
"Jaguar",
"Jetset",
"Wasteland rebel",
"The Empress",
"Elite Build" };
const char* p2000[] = { "none",
"Handgun",
"Fade",
"Corticera",
"Ocean Foam",
"Fire Elemental",
"Asterion",
"Pathfinder",
"Imperial",
"Oceanic",
"Imperial Dragon",
};
const char* revolver[] = { "none",
"Llama Cannon",
"Fade",
"Crimson Web",
"Reboot",
"Nitro",
"Bone Mask"
};
const char* knifemodels[]{ "Bayonet",
"Flip Knife",
"Gut Knife",
"Karambit",
"M9 Bayonet",
"Huntsman Knife",
"Butterfly Knife",
"Falchion Knife",
"Shadow Daggers",
"Bowie Knife",
"Navaja Knife",
"Stiletto Knife",
"Ursus Knife",
"Talon Knife" };
const char* knifeskin[] = { "none",
"Crimson Web",
"Bone Mask",
"Fade",
"Night",
"Blue Steel",
"Stained",
"Case Hardened",
"Slaughter",
"Safari Mesh",
"Boreal Forest",
"Ultraviolet",
"Urban Masked",
"Scorched",
"Rust Coat",
"Tiger Tooth",
"Damascus Steel",
"Damascus Steel",
"Marble Fade",
"Rust Coat",
"Doppler Ruby",
"Doppler Sapphire",
"Doppler Blackpearl",
"Doppler Phase 1",
"Doppler Phase 2",
"Doppler Phase 3",
"Doppler Phase 4",
"Gamma Doppler Phase 1",
"Gamma Doppler Phase 2",
"Gamma Doppler Phase 3",
"Gamma Doppler Phase 4",
"Gamma Doppler Emerald",
"Lore",
"Black Laminate",
"Autotronic",
"Freehand",
"Doppler_1new",
"Doppler_2new",
"Doppler_3new",
"Doppler_4new",
"Marble Fade_new",
"Damascus Steel_1new",
"Damascus Steel_2new" };
